from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable
import threading

@dataclass(frozen=True)
class NodeLabelStyle:
    template: str = ...
    missing: str = ...

class Client:
    event_id: int | None
    def __init__(
        self,
        host: str = ...,
        http_port: int = ...,
        grpc_port: int = ...,
        timeout: float = ...,
        grpc_secure: bool = ...,
        transport: str | None = ...,
    ) -> None: ...
    def emit(
        self,
        type_: str,
        parents: list[int] | None = ...,
        message: str | None = ...,
        payload: dict[str, Any] | list[Any] | None = ...,
    ) -> int: ...
    def health(self) -> bool: ...
    def get_event(self, event_id: int) -> dict[str, Any]: ...
    def children(self, event_id: int) -> list[int]: ...
    def ancestors(self, event_id: int) -> list[int]: ...
    def descendants(self, event_id: int, view: str = ...) -> dict[str, Any]: ...
    def descendants_batch(self, event_ids: list[int], view: str = ...) -> list[dict[str, Any]]: ...
    def provenance(self, event_id: int, view: str = ...) -> dict[str, Any]: ...
    def provenance_batch(self, event_ids: list[int], view: str = ...) -> list[dict[str, Any]]: ...
    def roots(self) -> list[int]: ...
    def heads(self) -> list[int]: ...
    def snapshot(self) -> dict[str, Any]: ...
    def version(self) -> dict[str, Any]: ...
    def subscribe(self, on_event: Callable[[dict[str, Any]], None], daemon: bool = ...) -> threading.Thread: ...

class NullClient:
    event_id: int | None
    def __init__(self, event_id: Any = ...) -> None: ...
    def emit(self, *args: Any, **kwargs: Any) -> int: ...
    def health(self) -> bool: ...
    def get_event(self, event_id: int) -> dict[str, Any]: ...
    def children(self, event_id: int) -> list[int]: ...
    def ancestors(self, event_id: int) -> list[int]: ...
    def descendants(self, event_id: int, view: str = ...) -> dict[str, Any]: ...
    def descendants_batch(self, event_ids: list[int], view: str = ...) -> list[dict[str, Any]]: ...
    def provenance(self, event_id: int, view: str = ...) -> dict[str, Any]: ...
    def roots(self) -> list[int]: ...
    def heads(self) -> list[int]: ...

def format_descendants_forest(
    forest: list[dict[str, Any]],
    label_style: NodeLabelStyle = ...,
) -> str: ...

def format_provenance_forest(
    forest: dict[str, Any] | list[dict[str, Any]],
    label_style: NodeLabelStyle = ...,
) -> str: ...
