from typing import Any, Callable, Type

class MarkDecorator:
    def __call__(self, func: Callable[..., Any]) -> Callable[..., Any]: ...

class _MarkModule:
    parametrize: Any
    skip: MarkDecorator
    skipif: Any
    xfail: Any
    def __getattr__(self, name: str) -> Any: ...

mark: _MarkModule

class _RaisesContext:
    def __enter__(self) -> _RaisesContext: ...
    def __exit__(self, *args: Any) -> bool: ...

def raises(expected_exception: Type[BaseException], *args: Any, **kwargs: Any) -> _RaisesContext: ...
def fixture(*args: Any, **kwargs: Any) -> Any: ...
def param(*args: Any, **kwargs: Any) -> Any: ...
def approx(expected: Any, rel: Any = ..., abs: Any = ..., nan_ok: bool = ...) -> Any: ...
